import { ProjectModel } from '@/models/project'

export const getAllProjects = async (): Promise<ProjectModel[]> => {
	return [
		{
			name: 'Beverage Store System',
			slug: 'beverage-store-system',
			repoUrl: 'https://github.com/orgs/VT-Store-Manager/repositories',
			image: '/project1.png',
			mainColor: 'orange',
			description:
				'Built a complete ordering system for a chain café, including customer, store, and delivery apps with real-time updates.',
			websiteUrl: '',
			techStack: [
				'NodeJS',
				'NestJS',
				'MongoDB',
				'Redis',
				'Socket.IO',
				'VueJS',
				'NuxtJS',
				'Vuetify',
				'Typescript',
				'Pinia',
				'SCSS',
				'Momo',
				'Twilio',
				'Google Map API',
				'AWS S3',
				'Swagger',
				'Postman',
			],
		},
		{
			name: 'Horse Racing Portal',
			slug: 'horse-racing-portal',
			repoUrl: '',
			image: '/project2.png',
			mainColor: 'blue',
			description:
				'Providing outsourcing services to renew user interface, develop new features and CMS for engaging more users, increasing business turnover and reducing monthly operating cost.',
			websiteUrl: 'https://tospo-keiba.jp',
			techStack: [
				'VueJS',
				'Typescript',
				'Pinia',
				'SCSS',
				'Laravel',
				'PostgreSQL',
				'Redis',
				'AWS',
			],
		},
		{
			name: 'My Portfolio',
			slug: 'horse-racing-portal',
			repoUrl: '',
			image: '/project3.png',
			mainColor: 'gray',
			description:
				'Providing outsourcing services to renew user interface, develop new features and CMS for engaging more users, increasing business turnover and reducing monthly operating cost.',
			websiteUrl: 'https://tospo-keiba.jp',
			techStack: [
				'NextJS',
				'ReactJS',
				'Typescript',
				'Redux',
				'Tailwind',
				'Canvas',
				'GSAP',
				'Storybook',
				'Postgres',
				'AWS',
			],
		},
		{
			name: 'VKN Social Media',
			slug: 'horse-racing-portal',
			repoUrl: '',
			image: '/project4.png',
			mainColor: 'pink',
			description:
				'Providing outsourcing services to renew user interface, develop new features and CMS for engaging more users, increasing business turnover and reducing monthly operating cost.',
			websiteUrl: 'https://tospo-keiba.jp',
			techStack: [
				'NextJS',
				'ReactJS',
				'Typescript',
				'Redux',
				'Tailwind',
				'Canvas',
				'GSAP',
				'Storybook',
				'Postgres',
				'AWS',
			],
		},
	]
}
